baseURL = 'https://florianheiwig.de/'
languageCode = 'en-us'
title = 'Florian G. Heiwig'
relativeURLs = false
uglyURLs = false

[params]
  description = "Berlin-based product professional, software developer, and entrepreneur."
  author = "Florian G. Heiwig"
  # Google Tag Manager container ID
  gtmContainerID = "GTM-MP6LZF49"
