baseURL = '/'
languageCode = 'en-us'
title = 'Florian G. Heiwig'
relativeURLs = true
uglyURLs = false

[params]
  description = "Berlin-based product professional, software developer, and entrepreneur."
  author = "Florian G. Heiwig"
  # Add your Google Tag Manager container ID (example: GTM-ABC1234)
  gtmContainerID = "GTM-MP6LZF49"
