baseURL = 'https://florianheiwig.de/'
languageCode = 'en-us'
title = 'Florian Heiwig'
relativeURLs = true
uglyURLs = false

[params]
  description = "Berlin-based product professional, software developer, and entrepreneur."
  author = "Florian Heiwig"
