baseURL = 'https://florianheiwig.de/blog/'
languageCode = 'en-us'
title = 'Florian Heiwig'

[params]
  description = "Berlin-based product professional, software developer, and entrepreneur."
  author = "Florian Heiwig"
